name: Publish Docker

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@3.04
        with:
          registry: docker.pkg.github.com
          name: docker.pkg.github.com/demianeen/top-app/top-app
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: "develop"
